version: "2"

run:
  timeout: 5m
  tests: false
  skip-dirs-use-default: true
  skip-files:
    - ".*mock\\.go$"
    - ".*test\\.go$"

output:
  sort-results: true
  print-linter-name: true

linters:
  disable-all: false
  fast: false
  enable:
    # Error handling
    - errcheck
    - errorlint
    - gosec
    
    # Code quality & performance
    - ineffassign
    - staticcheck
    - bodyclose
    - contextcheck
    - gocritic
    
    # Unused code detection
    - unused
    - unconvert
    - unparam
    
    # Complexity & duplication
    - gocyclo
    - gocognit
    - nestif
    - dupl
    - goconst
    
    # Go best practices
    - govet
    - prealloc
    - funlen
    - revive
    - goprintffuncname
    - godot
    - misspell
    - whitespace

formatters:
  enable:
    - goimports
    - gofmt

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  goconst:
    min-len: 2
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  nestif:
    min-complexity: 15
  
  funlen:
    lines: 100
    ignore-comments: true
  
  revive:
    ignore-generated-header: true
    severity: warning
