version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - errorlint
    - gosec
    - ineffassign
    - staticcheck
    - bodyclose
    - contextcheck
    - gocritic
    - unused
    - unconvert
    - unparam
    - gocyclo
    - gocognit
    - nestif
    - dupl
    - goconst
    - govet
    - prealloc
    - funlen
    - revive
    - goprintffuncname
    - godot
    - misspell
    - whitespace
